spring:
  rabbitmq:
    addresses: ${sc.rabbitmq.addresses}
    port: ${sc.rabbitmq.port}
    username: ${sc.rabbitmq.username}
    password: ${sc.rabbitmq.password}
    #连接到代理时用的虚拟主机
    virtual-host: ${sc.rabbitmq.virtual-host}
    #是否启用发布确认
    publisher-returns: false
    #异步回调
    publisher-confirm-type: correlated
    #心跳时间 s
    requested-heartbeat: 60
    #连接超时 ms 队列属性设置 与 消息进行单独设置 => 以两者之间TTL较小的那个数值为准
    connection-timeout: 300000
    #Template
    template:
      #启用强制信息
      mandatory: true
    #linstener
    listener:
      simple:
        #手动设置ack
        acknowledge-mode: manual
        concurrency: 3 #消费者最小数量
        max-concurrency: 10 # 消费者最大数量
        prefetch: 1 #一个消费者最多可处理的nack消息（消费者拒绝或处理异常的无法处理的消息）数量，如果有事务的话，必须大于等于transaction数量.
        retry:
          #开启消费重试
          enabled: true
          #重试三次
          max-attempts: 3
          #间隔时间
          initial-interval: 5000
        # 被拒绝的消息是否重新入队；默认是true
        default-requeue-rejected: true
